<script setup>
import {useComponentStore, useCreateWorkerStore} from "@/store/modules/index.js"
import validationRules from "@/utils/validationRules.js"
const store = useCreateWorkerStore()
const componentStore = useComponentStore()
const formRef = ref(null)

const onSubmit = ()=>{
  formRef.value?.validate((error)=>{
    if(!error) {
      store.save()
    }
  })
}

defineExpose({
  onSubmit
})

onMounted(()=>{
  componentStore._countries()
  componentStore._regions()
  componentStore._enums()
  componentStore._nationality()
})
</script>

<template>
  <n-form
      class="grid grid-cols-12 gap-x-4"
      ref="formRef"
      :rules="validationRules.personalForm"
      :model="store.payload"
  >
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.lastName`)"
        path="last_name">
      <n-input
          class="w-full"
          type="text"
          :placeholder="$t(`createWorkerPage.form.lastName`)"
          v-model:value="store.payload.last_name"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.firstName`)"
        path="first_name">
      <n-input
          class="w-full"
          type="text"
          :placeholder="$t(`createWorkerPage.form.firstName`)"
          v-model:value="store.payload.first_name"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.middleName`)"
        path="middle_name">
      <n-input
          class="w-full"
          type="text"
          :placeholder="$t(`createWorkerPage.form.middleName`)"
          v-model:value="store.payload.middle_name"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.country`)"
        path="country_id">
      <n-select
          v-model:value="store.payload.country_id"
          filterable
          :placeholder="$t(`createWorkerPage.form.country`)"
          :options="componentStore.countryList"
          label-field="name"
          value-field="id"
          :loading="componentStore.countryLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.region`)"
        path="region_id">
      <n-select
          v-model:value="store.payload.region_id"
          @update:value="store.changeRegion"
          filterable
          :placeholder="$t(`createWorkerPage.form.region`)"
          :options="componentStore.regionList"
          label-field="name"
          value-field="id"
          :loading="componentStore.regionLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.city`)"
        path="city_id">
      <n-select
          :disabled="!store.payload.region_id"
          v-model:value="store.payload.city_id"
          filterable
          :placeholder="$t(`createWorkerPage.form.city`)"
          :options="store.districtList"
          label-field="name"
          value-field="id"
          :loading="store.districtLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.currentRegion`)"
        path="current_region_id">
      <n-select
          v-model:value="store.payload.current_region_id"
          @update:value="store.changeCurrentRegion"
          filterable
          :placeholder="$t(`createWorkerPage.form.currentRegion`)"
          :options="componentStore.regionList"
          label-field="name"
          value-field="id"
          :loading="componentStore.regionLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.currentCity`)"
        path="current_city_id">
      <n-select
          :disabled="!store.payload.current_region_id"
          v-model:value="store.payload.current_city_id"
          filterable
          :placeholder="$t(`createWorkerPage.form.currentCity`)"
          :options="store.currentDistrictList"
          label-field="name"
          value-field="id"
          :loading="store.currentDistrictLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.birthday`)"
        path="birthday">
      <n-date-picker
          class="w-full"
          v-model:value="store.payload.birthday"
          type="date"
          :placeholder="$t(`createWorkerPage.form.birthday`)"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.address`)"
        path="address">
      <n-input
          class="w-full"
          type="text"
          :placeholder="$t(`createWorkerPage.form.address`)"
          v-model:value="store.payload.address"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.academicTitle`)"
        path="academic_title">
      <n-select
          v-model:value="store.payload.academic_title"
          filterable
          :placeholder="$t(`createWorkerPage.form.academicTitle`)"
          :options="componentStore.academicTitleList"
          label-field="name"
          value-field="id"
          :loading="componentStore.enumLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.academicDegree`)"
        path="academic_degree">
      <n-select
          v-model:value="store.payload.academic_degree"
          filterable
          :placeholder="$t(`createWorkerPage.form.academicDegree`)"
          :options="componentStore.academicDegreeList"
          label-field="name"
          value-field="id"
          :loading="componentStore.enumLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.nationality_id`)"
        path="nationality_id">
      <n-select
          v-model:value="store.payload.nationality_id"
          filterable
          :placeholder="$t(`createWorkerPage.form.nationality_id`)"
          :options="componentStore.nationalityList"
          label-field="name"
          value-field="id"
          :loading="componentStore.nationalityLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.party`)"
        path="party">
      <n-select
          v-model:value="store.payload.party"
          filterable
          :placeholder="$t(`createWorkerPage.form.party`)"
          :options="componentStore.partyList"
          label-field="name"
          value-field="id"
          :loading="componentStore.enumLoading"
      />
    </n-form-item>
    <n-form-item
        class="col-span-4"
        :label="$t(`createWorkerPage.form.pin`)"
        path="pin">
      <n-input
          class="w-full"
          type="text"
          :placeholder="$t(`createWorkerPage.form.pin`)"
          v-model:value="store.payload.pin"
          v-mask="`####-####-####-##`"
      />
    </n-form-item>
  </n-form>
</template>

<style scoped>

</style>