export const NotificationPage = () => import('./notification/NotificationPage.vue')
export const NewsPage = () => import('./news/Page.vue')
export const NewsFormPage = () => import('./news/FormPage.vue')
export const ViewNewsPage = () => import('./news/ViewPage.vue')
export const NewsCategoryPage = () => import('./news-category/page.vue')
