import {AppPaths} from "@/utils/index.js";
import Utils from "@/utils/Utils.js";

import{
    PermissionPage,
    UserPage,
    RolePage,
    CountryPage,
    RegionPage,
    DistrictPage,
    NationalityPage,
    PositionPage,
    OrganizationPage,
    ActionLogPage,
    OthersPage,
    SchedulePage,
    WorkdayPage,
    DocumentTemplate,
    HolidayPage,
    TelegramPage,
    LearningCenterPage,
    InstructionPage,
} from "@/pages/admin/index.js"


export default  [
    {
        path:Utils.routePathMaker(AppPaths.UserPermission),
        name:AppPaths.UserPermission.substring(1),
        component:PermissionPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.User),
        name:AppPaths.User.substring(1),
        component:UserPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.UserRole),
        name:AppPaths.UserRole.substring(1),
        component:RolePage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Country),
        name:AppPaths.Country.substring(1),
        component:CountryPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Region),
        name:AppPaths.Region.substring(1),
        component:RegionPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.District),
        name:AppPaths.District.substring(1),
        component:DistrictPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Nationality),
        name:AppPaths.Nationality.substring(1),
        component:NationalityPage,
        
    },
    {
        path:Utils.routePathMaker(AppPaths.Position),
        name:AppPaths.Position.substring(1),
        component:PositionPage,
       
    },
    {
        path:Utils.routePathMaker(AppPaths.Organizations),
        name:AppPaths.Organizations.substring(1),
        component:OrganizationPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.ActionLog),
        name:AppPaths.ActionLog.substring(1),
        component:ActionLogPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.DocumentSetting),
        name:AppPaths.DocumentSetting.substring(1),
        component:DocumentTemplate,             
    },
    {
        path:Utils.routePathMaker(AppPaths.AdminOther),
        name:AppPaths.AdminOther.substring(1),
        component:OthersPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Schedule),
        name:AppPaths.Schedule.substring(1),
        component:SchedulePage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Workday),
        name:AppPaths.Workday.substring(1),
        component:WorkdayPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Holiday),
        name:AppPaths.Holiday.substring(1),
        component:HolidayPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Telegram),
        component:TelegramPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.LearningCenter),
        name:AppPaths.LearningCenter.substring(1),
        component:LearningCenterPage,
    },
    {
        path:Utils.routePathMaker(AppPaths.Instruction),
        name:AppPaths.Instruction.substring(1),
        component:InstructionPage,
    },
]