import {AppLayouts, AppPaths} from "@/utils/index.js"
import Utils from "@/utils/Utils.js"
import {
    PensionerPage,
    PolyclinicPage,
    VacancyPage,
    WorkerPage,
    DepartmentPage,
    DepartmentPositionPage,
    CandidatePage,
    ConfirmationPage,
    ProfilePage,
    VacationPage,
    TimesheetDepartmentPage,
    DashboardV3Page,
    TimesheetListPage,
    MedPage,
    SlicePage,
    OrganizationLeaderPage,
    ExportPage,
    BusinessTripPage,
    DocumentArchivePage,
    VacationSchedule,
    UserRolePage,
    PunishmentPage,
    IncentivePage,
    ReportPage,
    OtherPage,
} from "@/pages/hrm/index.js"

import {
    LmsWorkerPage,
} from "@/pages/lms/index.js"

import {
    ApplicationPage,
    CommandPage,
    AdContractPage,
    ContractPage,
} from "@/pages/docFlow/index.js"

export default [
    {
        path:Utils.routeHrmPathMaker(AppPaths.Worker),
        name:AppPaths.Worker.substring(1),
        component:WorkerPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Department),
        name:AppPaths.Department.substring(1),
        component:DepartmentPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.DepartmentPosition),
        name:AppPaths.DepartmentPosition.substring(1),
        component:DepartmentPositionPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(`${AppPaths.Worker}${AppPaths.Create}`),
        name:`${AppPaths.Worker.substring(1)}-${AppPaths.Create.substring(1)}`,
        component:CandidatePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Confirmation),
        name:AppPaths.Confirmation.substring(1),
        component:ConfirmationPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.WorkerProfile),
        name:AppPaths.WorkerProfile.substring(1),
        component: ProfilePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Application),
        name:AppPaths.Application.substring(1),
        component: ApplicationPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Command),
        name:AppPaths.Command.substring(1),
        component:CommandPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.AdContract),
        name:AppPaths.AdContract.substring(1),
        component:AdContractPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Contract),
        name:AppPaths.Contract.substring(1),
        component:ContractPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Vacation),
        name:AppPaths.Vacation.substring(1),
        component:VacationPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Dashboard),
        name:AppPaths.Dashboard.substring(1),
        component:DashboardV3Page,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.TimesheetDepartment),
        name:AppPaths.TimesheetDepartment.substring(1),
        component:TimesheetDepartmentPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.TimeSheet),
        name:AppPaths.TimeSheet.substring(1),
        component:TimesheetListPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Med),
        name:AppPaths.Med.substring(1),
        component:MedPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Slice),
        name:AppPaths.Slice.substring(1),
        component:SlicePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.OrganizationLeader),
        component:OrganizationLeaderPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Export),
        component:ExportPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.BusinessTrip),
        component:BusinessTripPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.DocumentArchive),
        component:DocumentArchivePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.VacationSchedule),
        component:VacationSchedule,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.WorkerRole),
        component:UserRolePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Punishment),
        component:PunishmentPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Incentive),
        component:IncentivePage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Report),
        component:ReportPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Polyclinic),
        component:PolyclinicPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.PublicVacancy),
        component:VacancyPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Pensioner),
        component:PensionerPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.LmsWorker),
        component:LmsWorkerPage,
        meta:{
            layout:AppLayouts.main
        },
    },
    {
        path:Utils.routeHrmPathMaker(AppPaths.Other),
        name:AppPaths.Other.substring(1),
        component:OtherPage,
        meta:{
            layout:AppLayouts.main
        },
    },
]
