export const AppPaths = {
    Main:'/',
    Admin:"/admin",
    Chat:"/chat",
    Lms:"/lms",
    DocFlow:"/docflow",
    Hrm:"/hrm",
    OrganizationLayout:'/organization-layout',
    Home:"/home",
    Dashboard:'/dashboard',
    Product:"/product",
    Category:"/category",
    Login:'/login',
    Register:'/register',
    VerificationEmail:'/verification-email',
    RegisterService:"/register-service",
    Client:"/client",
    UserPermission:"/user-permission",
    User:"/user",
    UserRole:"/user-role",
    Country:"/country",
    Region:"/region",
    District:"/district",
    Nationality:"/nationality",
    Profile:"/profile",
    Position:"/position",
    Organizations:"/organizations",
    Worker:"/worker",
    Contact:"/contact",
    DocumentHistory:"/document-history",
    Exam:"/exam",
}

export const AppLayouts ={
    empty:"empty",
    main:"main",
}