export const appPermissions = {
  users: 'users',
  admin: 'admin',
  // Admin modulidagi ayrim sahifalar uchun ALOHIDA sluglar — ilgari ular
  // `admin` (module-access) bilan gate qilingan edi, ya'ni bandni ko'rish
  // uchun butun Admin moduli ochilishi kerak edi (juda qo'pol).
  mobileUsers: 'mobile-users',
  mobileUsersRead: 'mobile-users-read',
  integrationClients: 'integration-clients',
  integrationClientsRead: 'integration-clients-read',
  dbBackupRead: 'db-backup-read',
  integrationClientsWrite: 'integration-clients-write',
  holidayGreetings: 'holiday-greetings',
  holidayGreetingsRead: 'holiday-greetings-read',
  holidayGreetingsWrite: 'holiday-greetings-write',
  usersWrite: 'users-write',
  usersRead: 'users-read',

  roles: 'roles',
  rolesRead: 'roles-read',
  rolesWrite: 'roles-write',

  permissions: 'permissions',
  permissionsRead: 'permissions-read',
  permissionsWrite: 'permissions-write',

  countries: 'countries',
  countriesRead: 'countries-read',
  countriesWrite: 'countries-write',

  regions: 'regions',
  regionsRead: 'regions-read',
  regionsWrite: 'regions-write',

  cities: 'cities',
  citiesRead: 'cities-read',
  citiesWrite: 'cities-write',

  organizations: 'organizations',
  organizationsRead: 'organizations-read',
  organizationsWrite: 'organizations-write',

  documentExamples: 'document-examples',
  documentExamplesRead: 'document-examples-read',
  documentExamplesWrite: 'document-examples-write',

  organizationServices: 'organization-services',
  organizationServicesRead: 'organization-services-read',
  organizationServicesWrite: 'organization-services-write',

  organizationAdmin: 'organization-admin',
  organizationLeader: 'organization-leader',
  organization: 'organization',
  holidays: 'holidays',
  holidaysWrite: 'holidays-write',
  holidaysRead: 'holidays-read',
  universities: 'universities',
  universitiesWrite: 'universities-write',
  universitiesRead: 'universities-read',
  specialities: 'specialities',
  specialitiesWrite: 'specialities-write',
  specialitiesRead: 'specialities-read',
  languages: 'languages',
  languagesWrite: 'languages-write',
  languagesRead: 'languages-read',
  telegram: 'telegram',
  telegramWrite: 'telegram-write',
  telegramRead: 'telegram-read',
  vacancyApprove: 'vacancy-approve',
  vacancyApproveWrite: 'vacancy-approve-write',
  vacancyApproveRead: 'vacancy-approve-read',
  workerReports: 'worker-reports',
  workerReportsRead: 'worker-reports-read',
  learningCenters: 'learning-centers',
  learningCentersWrite: 'learning-centers-write',
  learningCentersRead: 'learning-centers-read',

  nationalities: 'nationalities',
  nationalitiesWrite: 'nationalities-write',
  nationalitiesRead: 'nationalities-read',
  positions: 'positions',
  positionsWrite: 'positions-write',
  positionsRead: 'positions-read',
  schedules: 'schedules',
  schedulesWrite: 'schedules-write',
  schedulesRead: 'schedules-read',
  workDay: 'work-day',
  workDayWrite: 'work-day-write',
  workDayRead: 'work-day-read',
  activityLogs: 'activity-logs',
  activityLogsWrite: 'activity-logs-write',
  activityLogsRead: 'activity-logs-read',
  instructions: 'instructions',
  instructionsWrite: 'instructions-write',
  instructionsRead: 'instructions-read',

  hr: 'hr',
  hrDashboard: 'hr-dashboard',
  hrDashboardRead: 'hr-dashboard-read',
  hrDashboardAudit: 'hr-dashboard-audit',

  hrArchiveRead: 'hr-archive-read',
  hrArchiveResume: 'hr-archive-resume',
  hrWorkers: 'hr-workers',
  hrWorkersWrite: 'hr-workers-write',
  hrWorkersPassword: 'hr-workers-password',
  hrWorkersRead: 'hr-workers-read',
  // JSHSHIR bo'yicha xodimni tekshirish (`GET /hr/check-worker`) — xodim qo'shishda
  // va turniket kartochkasida ishlatiladi. Backend @Permission bilan enforce qiladi.
  hrCheckWorker: 'hr-check-worker',

  // O'zgarishlar tarixida maskalangan qiymatni (JSHSHIR, pasport seriyasi)
  // to'liq ko'rish. Migratsiya 0106 da yaratiladi va faqat Admin roliga beriladi.
  auditUnmask: 'audit-unmask',
  // Kengaytirilgan xodim qidiruvi (`GET /hr/search-workers`).
  filterSearchWorkers: 'filter-search-workers',

  // Guvohnomalar ro'yxati sahifasi — xodimlar ruxsatidan AJRALGAN.
  hrCertificatesRead: 'hr-certificates-read',

  // KPI ko'rsatgichlar sahifasi (HR moduli).
  hrKpi: 'hr-kpi',
  hrKpiRead: 'hr-kpi-read',

  hrDepartments: 'hr-departments',
  hrDepartmentsWrite: 'hr-departments-write',
  hrDepartmentsRead: 'hr-departments-read',

  hrPositions: 'hr-positions',
  hrPositionsWrite: 'hr-positions-write',
  hrPositionsRead: 'hr-positions-read',

  hrContracts: 'hr-contracts',
  hrContractsWrite: 'hr-contracts-write',
  hrContractsRead: 'hr-contracts-read',

  hrCommands: 'hr-commands',
  hrCommandsWrite: 'hr-commands-write',
  hrCommandsRead: 'hr-commands-read',
  hrCommandsBlank: 'hr-commands-blank',

  hrContractAdditional: 'hr-contract-additional',
  hrContractAdditionalWrite: 'hr-contract-additional-write',
  hrContractAdditionalRead: 'hr-contract-additional-read',

  hrWorkerApplications: 'hr-worker-applications',
  hrWorkerApplicationsWrite: 'hr-worker-applications-write',
  hrWorkerApplicationsRead: 'hr-worker-applications-read',

  hrConfirmations: 'hr-confirmations',
  hrConfirmationsWrite: 'hr-confirmations-write',
  hrConfirmationsRead: 'hr-confirmations-read',

  hrVacations: 'hr-vacations',
  hrVacationsWrite: 'hr-vacations-write',
  hrVacationsRead: 'hr-vacations-read',

  hrTableWorkers: 'hr-table-workers',
  hrTableWorkersWrite: 'hr-table-workers-write',
  hrTableWorkersRead: 'hr-table-workers-read',

  hrTable: 'hr-table',
  hrTableWrite: 'hr-table-write',
  hrTableRead: 'hr-table-read',

  hrMed: 'hr-med',
  hrMedWrite: 'hr-med-write',
  hrMedRead: 'hr-med-read',

  hrLeaders: 'hr-leaders',
  hrLeadersWrite: 'hr-leaders-write',
  hrLeadersRead: 'hr-leaders-read',

  hrExport: 'hr-export',

  hrBusinessTrip: 'hr-business-trip',
  hrBusinessTripWrite: 'hr-business-trip-write',
  hrBusinessTripRead: 'hr-business-trip-read',

  hrDocuments: 'hr-documents',
  hrDocumentsWrite: 'hr-documents-write',
  hrDocumentsRead: 'hr-documents-read',

  hrVacationSchedule: 'hr-vacation-schedule',
  hrVacationScheduleWrite: 'hr-vacation-schedule-write',
  hrVacationScheduleRead: 'hr-vacation-schedule-read',

  hrUsers: 'hr-users',
  hrUsersWrite: 'hr-users-write',
  hrUsersRead: 'hr-users-read',
  // Foydalanuvchilar menyusi — per-option (har amal alohida ruxsat)
  hrUsersAttachRole: 'hr-users-attach-role',
  hrUsersDetachRole: 'hr-users-detach-role',
  hrUsersActiveRole: 'hr-users-active-role',
  hrUsersPassword: 'hr-users-password',
  hrUsersUpdate: 'hr-users-update',

  hrPublicVacancy: 'hr-public-vacancy',
  hrPublicVacancyWrite: 'hr-public-vacancy-write',
  hrPublicVacancyRead: 'hr-public-vacancy-read',

  hrReport: 'hr-report',
  hrReportWrite: 'hr-report-write',
  hrReportRead: 'hr-report-read',
  hrReportManagementWrite: 'hr-report-management-write',
  hrReportStaffingExport: 'hr-report-staffing-export',

  hrReportExport: 'hr-report-export',
  hrReportExportWrite: 'hr-report-export-write',
  hrReportExportRead: 'hr-report-export-read',

  confirmation: 'confirmation',
  confirmationContracts: 'confirmation-contracts',
  confirmationAddContracts: 'confirmation-contract-additional',
  confirmationCommands: 'confirmation-commands',
  confirmationWorkerApplications: 'confirmation-worker-applications',
  confirmationTable: 'confirmation-table',
  confirmationLmsCertificate: 'confirmation-lms-certificate',
  confirmationLmsCertificateRead: 'confirmation-lms-certificate-read',
  confirmationLmsCertificateWrite: 'confirmation-lms-certificate-write',
  confirmationStaffingApproval: 'confirmation-staffing-approval',

  exam: 'exam',

  examTopics: 'exam-topics',
  examTopicsWrite: 'exam-topics-write',
  examTopicsRead: 'exam-topics-read',

  examCategories: 'exam-categories',
  examCategoriesWrite: 'exam-categories-write',
  examCategoriesRead: 'exam-categories-read',

  examExams: 'exam-exams',
  examExamsWrite: 'exam-exams-write',
  examExamsRead: 'exam-exams-read',

  examResults: 'exam-results',
  examResultsWrite: 'exam-results-write',
  examResultsRead: 'exam-results-read',

  turnstile: 'turnstile',
  turnstileBuilding: 'turnstile-building',
  turnstileBuildingWrite: 'turnstile-building-write',
  turnstileBuildingRead: 'turnstile-building-read',
  turnstileTerminal: 'turnstile-terminal',
  turnstileTerminalRead: 'turnstile-terminal-read',
  turnstileTerminalWrite: 'turnstile-terminal-write',
  turnstileOrganization: 'turnstile-organization',
  turnstileOrganizationWrite: 'turnstile-organization-write',
  turnstileOrganizationRead: 'turnstile-organization-read',
  turnstileWorkers: 'turnstile-workers',
  turnstileWorkersWrite: 'turnstile-workers-write',
  turnstileWorkersRead: 'turnstile-workers-read',
  turnstileWorkDuration: 'turnstile-work-duration',
  turnstileWorkDurationRead: 'turnstile-work-duration-read',
  turnstileWorkDurationWrite: 'turnstile-work-duration-write',
  turnstileWorkDurationShow: 'turnstile-work-duration-show',
  turnstileWorkDurationLogs: 'turnstile-work-duration-logs',
  hrJobs: 'hr-jobs',
  hrJobsWrite: 'hr-jobs-write',
  hrJobsRead: 'hr-jobs-read',
  hrMonthlyReport: 'hr-monthly-report',
  exportWorkersZip: 'export-workers-zip',

  turnstileAccessLevels: 'turnstile-access-levels',
  turnstileAccessLevelsRead: 'turnstile-access-levels-read',
  turnstileAccessLevelsWrite: 'turnstile-access-levels-write',
  // «Sinxronlash» — Tahrirlashdan ajratilgan (audit 2026-08-12).
  turnstileAccessLevelsSync: 'turnstile-access-levels-sync',
  turnstileOrganizationAccessLevels: 'turnstile-organization-access-levels',
  turnstileOrganizationAccessLevelsRead: 'turnstile-organization-access-levels-read',
  turnstileOrganizationAccessLevelsWrite: 'turnstile-organization-access-levels-write',
  turnstileHikCentralWorkers: 'turnstile-hik-central-workers',
  turnstileHikCentralWorkersRead: 'turnstile-hik-central-workers-read',
  turnstileHikCentralWorkersWrite: 'turnstile-hik-central-workers-write',
  turnstileHikCentralJob: 'turnstile-hik-central-job',
  turnstileHikCentralJobWrite: 'turnstile-hik-central-job-write',
  turnstileHikCentralJobRead: 'turnstile-hik-central-job-read',
  turnstileHikCentralEvents: 'turnstile-hik-central-events',
  turnstileHikCentralEventsRead: 'turnstile-hik-central-events-read',
  turnstileHikCentralEventsWrite: 'turnstile-hik-central-events-write',
  turnstileAbsentWorkersExport: 'turnstile-absent-workers-export',
  turnstileHikCentralTgUser: 'turnstile-hik-central-tg-user',
  turnstileHikCentralTgUserRead: 'turnstile-hik-central-tg-user-read',
  turnstileHikCentralTgUserWrite: 'turnstile-hik-central-tg-user-write',
  turnstileWorkerImage: 'turnstile-worker-image',
  turnstileWorkerImageRead: 'turnstile-worker-image-read',
  turnstileWorkerImageWrite: 'turnstile-worker-image-write',
  turnstileHikCentralSync: 'turnstile-hik-central-sync',
  turnstileHikCentralSyncWrite: 'turnstile-hik-central-sync-write',
  turnstileHikCentralSyncRead: 'turnstile-hik-central-sync-read',
  turnstileHikCentralUserImageLogs: 'turnstile-hc-user-image-logs',
  turnstileHikCentralInvalidUser: 'turnstile-hc-invalid-user',
  turnstileDevices: 'turnstile-devices',
  // Qurilmalar sahifasidagi ikki yuklash tugmasi — alohida boshqariladi.
  turnstileDevicesExport: 'turnstile-devices-export',
  turnstileDevicesStatExport: 'turnstile-devices-stat-export',
  turnstileDevicesRead: 'turnstile-devices-read',
  turnstileDevicesWrite: 'turnstile-devices-write',
  turnstileDevicesSync: 'turnstile-devices-sync',
  turnstileOthers: 'turnstile-others',
  turnstileApprove: 'turnstile-approve',
  turnstileApproveRead: 'turnstile-approve-read',
  turnstileApproveWrite: 'turnstile-approve-write',

  hrIncentives: 'hr-incentives',
  hrIncentivesWrite: 'hr-incentives-write',
  hrIncentivesRead: 'hr-incentives-read',

  hrTasks: 'hr-tasks',
  hrTasksRead: 'hr-tasks-read',
  hrTasksWrite: 'hr-tasks-write',
  hrTasksDelete: 'hr-tasks-delete',

  hrPunishment: 'hr-discips',
  hrPunishmentWrite: 'hr-discips-write',
  hrPunishmentRead: 'hr-discips-read',
  turnstileDashboard: 'turnstile-dashboard',
  turnstileDashboardRead: 'turnstile-dashboard-read',
  turnstileDashboardWrite: 'turnstile-dashboard-write',
  // Dashboard preview Excel yuklash — ko'rishdan ajratilgan (audit 2026-08-12).
  turnstileDashboardExport: 'turnstile-dashboard-export',

  turnstileHcpDuration: 'turnstile-hcp-duration',
  turnstileHcpDurationShow: 'turnstile-hcp-duration-show',
  turnstileHcpDurationWrite: 'turnstile-hcp-duration-write',
  turnstileHcpDurationRead: 'turnstile-hcp-duration-read',

  turnstileSheetsGroupsWrite: 'turnstile-sheets-groups-write',
  turnstileSheetsGroupsRead: 'turnstile-sheets-groups-read',
  turnstileSheetsGroups: 'turnstile-sheets-groups',
  // «Smena guruhlari» → «Yakunlash» — alohida (audit 2026-08-12).
  turnstileSheetsGroupsFinish: 'turnstile-sheets-groups-finish',
  turnstileSheetsWrite: 'turnstile-sheets-write',
  turnstileSheetsRead: 'turnstile-sheets-read',
  turnstileSheets: 'turnstile-sheets',
  // «Navbatchilik grafigi» dagi «Tabel yuklash» — tahrirlashdan ajratilgan.
  turnstileSheetsTimesheetExport: 'turnstile-sheets-timesheet-export',
  // «Navbatchilik grafigi» row amallari — alohida (audit 2026-08-12).
  turnstileSheetsCopy: 'turnstile-sheets-copy',
  turnstileSheetsTurnstile: 'turnstile-sheets-turnstile',
  turnstileSheetsReplace: 'turnstile-sheets-replace',
  // «Turniket grafiki» — alohida sahifa (ilgari `turnstile-sheets` bilan bir edi).
  turnstileSchedule: 'turnstile-schedule',
  turnstileScheduleRead: 'turnstile-schedule-read',
  // «Turniket grafiki» — sahifada «Tahrirlash» yo'q; ikki amal bor:
  // «Qurilma biriktirish» (write) va «Ish vaqti faktini tekshirish» (check).
  turnstileScheduleWrite: 'turnstile-schedule-write',
  turnstileScheduleCheck: 'turnstile-schedule-check',
  turnstileSheetsWorkersWrite: 'turnstile-sheets-workers-write',
  turnstileSheetsWorkersRead: 'turnstile-sheets-workers-read',
  turnstileSheetsWorkers: 'turnstile-sheets-workers',

  hospital: 'hospital',
  hospitalExpired: 'hospital-expired',
  hospitalExpiredWrite: 'hospital-expired-write',
  hospitalExpiredRead: 'hospital-expired-read',
  hospitalTicket: 'hospital-ticket',
  hospitalTicketWrite: 'hospital-ticket-write',
  hospitalTicketRead: 'hospital-ticket-read',
  hospitalPensioner: 'hospital-pensioner',
  hospitalPensionerRead: 'hospital-pensioner-read',
  hospitalPensionerWrite: 'hospital-pensioner-write',

  useful: 'useful',
  ai: 'ai',
  economist: 'economist',
  // Oylik (salary-1c) bo'limi — faqat admin belgilagan xodimlar (tor ruxsat, migr 0077).
  salary1cAccess: 'salary-1c-access',
  // Tarif setkasi (tariff-grid) — faqat admin belgilagan xodimlar (tor ruxsat, migr 0080).
  tariffGridAccess: 'tariff-grid-access-read',
  economistDashboard: 'economist-dashboard-read',
  economistWorkerCategories: 'economist-worker-categories',
  economistWorkerCategoriesRead: 'economist-worker-categories-read',
  economistWorkerCategoriesWrite: 'economist-worker-categories-write',
  economistStatements: 'economist-statements',
  economistStatementsWrite: 'economist-statements-write',
  economistStatementsRead: 'economist-statements-read',
  economistStatementsCode: 'economist-statements-code',
  economistTaxFour: 'economist-tax-four',
  economistTaxFourWrite: 'economist-tax-four-write',
  economistTaxFourRead: 'economist-tax-four-read',
  economistTaxFive: 'economist-tax-five',
  economistTaxFiveWrite: 'economist-tax-five-write',
  economistTaxFiveRead: 'economist-tax-five-read',
  economistPensionPayments: 'economist-pension-payments',
  economistPensionPaymentsWrite: 'economist-pension-payments-write',
  economistPensionPaymentsRead: 'economist-pension-payments-read',
  economistUploads: 'economist-uploads',
  economistUploadsWrite: 'economist-uploads-write',
  economistUploadsRead: 'economist-uploads-read',
  economistUploadsConfirm: 'economist-uploads-confirm',
  economistUploadsStatus: 'economist-uploads-status',
  economistStaffingApprove: 'economist-staffing-approve',
  economistStaffingApproveRead: 'economist-staffing-approve-read',
  economistStaffingApproveWrite: 'economist-staffing-approve-write',

  lms: 'lms',
  lmsDirection: 'lms-direction',
  lmsDirectionRead: 'lms-direction-read',
  lmsDirectionWrite: 'lms-direction-write',
  lmsSpecialization: 'lms-specialization',
  lmsSpecializationRead: 'lms-specialization-read',
  lmsSpecializationWrite: 'lms-specialization-write',
  lmsSubjects: 'lms-subjects',
  lmsSubjectsRead: 'lms-subjects-read',
  lmsSubjectsWrite: 'lms-subjects-write',
  lmsEduPlan: 'lms-edu-plan',
  lmsEduPlanRead: 'lms-edu-plan-read',
  lmsEduPlanWrite: 'lms-edu-plan-write',
  lmsEduPlanExport: 'lms-edu-plan-export',
  lmsTeachers: 'lms-teachers',
  lmsTeachersRead: 'lms-teachers-read',
  lmsTeachersWrite: 'lms-teachers-write',
  lmsGroups: 'lms-groups',
  lmsGroupsRead: 'lms-groups-read',
  lmsGroupsWrite: 'lms-groups-write',
  lmsLessons: 'lms-lessons',
  lmsLessonsRead: 'lms-lessons-read',
  lmsLessonsWrite: 'lms-lessons-write',
  lmsListenerRead: 'lms-listener-read',
  lmsResultRead: 'lms-result-read',
  lmsWorker: 'lms-worker',
  lmsWorkerRead: 'lms-worker-read',
  lmsWorkerWrite: 'lms-worker-write',
  lmsCertificate: 'lms-certificate',
  lmsCertificateRead: 'lms-certificate-read',
  lmsCertificateWrite: 'lms-certificate-write',

  chat: 'chat',
  chatTelegramMessages: 'chat-telegram-messages',
  chatNotification: 'chat-notification',

  extra: 'extra',
  extraWorkerUser: 'extra-worker-user',
  educationsStructureMenu: 'educations-structure-menu',

  departmentLocation: 'department-location',
  departmentLocationRead: 'department-location-read',
  departmentLocationWrite: 'department-location-write',

  // ─────────────────────────────────────────────────────────────────────────
  // Backend enforce qiladi, lekin frontendda konstantasi yo'q edi.
  // Quyidagilar `permissionGroups.js` dagi ENFORCED to'plamidan olingan —
  // ro'yxatni `npm run check:permissions` tekshirib turadi.
  // ─────────────────────────────────────────────────────────────────────────

  // To'liq yetishmayotgan oilalar (read/write/delete). Ilgari bu sahifalar
  // begona slug bilan (masalan `hrVacationsWrite`) tekshirilardi.
  hrPensioners: 'hr-pensioners',
  hrPensionersRead: 'hr-pensioners-read',
  hrPensionersWrite: 'hr-pensioners-write',

  hrLanguageCertificates: 'hr-language-certificates',
  hrLanguageCertificatesRead: 'hr-language-certificates-read',
  hrLanguageCertificatesWrite: 'hr-language-certificates-write',

  hrOrganizationPhones: 'hr-organization-phones',
  hrOrganizationPhonesRead: 'hr-organization-phones-read',
  hrOrganizationPhonesWrite: 'hr-organization-phones-write',

  quotesWrite: 'quotes-write',

  // O'chirish ruxsatlari (71 ta). Ilgari BITTASI ham yo'q edi: rol formasida
  // "O'chirish" switch'i chizilardi-yu, frontend uni hech qachon tekshirmasdi —
  // ya'ni huquqni berish/olib qo'yish hech qanday ta'sir qilmasdi.
  chatNewsDelete: 'chat-news-delete',
  citiesDelete: 'cities-delete',
  confirmationDocumentsDelete: 'confirmation-documents-delete',
  confirmationWorkerApplicationsDelete: 'confirmation-worker-applications-delete',
  countriesDelete: 'countries-delete',
  departmentLocationDelete: 'department-location-delete',
  economistPensionPaymentsDelete: 'economist-pension-payments-delete',
  economistStaffingApproveDelete: 'economist-staffing-approve-delete',
  economistStatementsDelete: 'economist-statements-delete',
  economistTaxFiveDelete: 'economist-tax-five-delete',
  economistTaxFourDelete: 'economist-tax-four-delete',
  economistWorkerCategoriesDelete: 'economist-worker-categories-delete',
  examCategoriesDelete: 'exam-categories-delete',
  examExamsDelete: 'exam-exams-delete',
  examTopicsDelete: 'exam-topics-delete',
  holidayGreetingsDelete: 'holiday-greetings-delete',
  holidaysDelete: 'holidays-delete',
  hrCommandsDelete: 'hr-commands-delete',
  hrConfirmationsDelete: 'hr-confirmations-delete',
  hrContractAdditionalDelete: 'hr-contract-additional-delete',
  hrContractsDelete: 'hr-contracts-delete',
  hrDepartmentsDelete: 'hr-departments-delete',
  hrDocumentsDelete: 'hr-documents-delete',
  hrLanguageCertificatesDelete: 'hr-language-certificates-delete',
  hrLeadersDelete: 'hr-leaders-delete',
  hrMedDelete: 'hr-med-delete',
  hrMonthlyReportDelete: 'hr-monthly-report-delete',
  hrOrganizationPhonesDelete: 'hr-organization-phones-delete',
  hrPensionersDelete: 'hr-pensioners-delete',
  hrPositionsDelete: 'hr-positions-delete',
  hrPublicVacancyDelete: 'hr-public-vacancy-delete',
  hrReportDelete: 'hr-report-delete',
  hrReportExportDelete: 'hr-report-export-delete',
  hrTableDelete: 'hr-table-delete',
  hrVacationScheduleDelete: 'hr-vacation-schedule-delete',
  hrWorkersDelete: 'hr-workers-delete',
  instructionsDelete: 'instructions-delete',
  integrationClientsDelete: 'integration-clients-delete',
  languagesDelete: 'languages-delete',
  learningCentersDelete: 'learning-centers-delete',
  lmsCertificateDelete: 'lms-certificate-delete',
  lmsDirectionDelete: 'lms-direction-delete',
  lmsEduPlanDelete: 'lms-edu-plan-delete',
  lmsLessonsDelete: 'lms-lessons-delete',
  lmsSpecializationDelete: 'lms-specialization-delete',
  lmsSubjectsDelete: 'lms-subjects-delete',
  lmsTeachersDelete: 'lms-teachers-delete',
  mobileStoriesDelete: 'mobile-stories-delete',
  nationalitiesDelete: 'nationalities-delete',
  organizationsDelete: 'organizations-delete',
  permissionsDelete: 'permissions-delete',
  positionsDelete: 'positions-delete',
  quotesDelete: 'quotes-delete',
  regionsDelete: 'regions-delete',
  rolesDelete: 'roles-delete',
  schedulesDelete: 'schedules-delete',
  specialitiesDelete: 'specialities-delete',
  turnstileApproveDelete: 'turnstile-approve-delete',
  turnstileBuildingDelete: 'turnstile-building-delete',
  turnstileDevicesDelete: 'turnstile-devices-delete',
  turnstileHikCentralTgUserDelete: 'turnstile-hik-central-tg-user-delete',
  turnstileHikCentralWorkersDelete: 'turnstile-hik-central-workers-delete',
  turnstileSheetsDelete: 'turnstile-sheets-delete',
  turnstileSheetsGroupsDelete: 'turnstile-sheets-groups-delete',
  turnstileSheetsWorkersDelete: 'turnstile-sheets-workers-delete',
  turnstileTerminalDelete: 'turnstile-terminal-delete',
  universitiesDelete: 'universities-delete',
  usersDelete: 'users-delete',
  vacancyApproveDelete: 'vacancy-approve-delete',
  workDayDelete: 'work-day-delete'
}
