export const AppPaths = {
    Main:'/',
    Admin:"/admin",
    Chat:"/chat",
    Lms:"/lms",
    Attestation:"/attestation",
    DocFlow:"/docflow",
    Hrm:"/hrm",
    OrganizationLayout:'/organization-layout',
    Home:"/home",
    Dashboard:'/dashboard',
    Product:"/product",
    Category:"/category",
    Login:'/login',
    Register:'/register',
    VerificationEmail:'/verification-email',
    RegisterService:"/register-service",
    Client:"/client",
    UserPermission:"/user-permission",
    User:"/user",
    UserRole:"/user-role",
    Country:"/country",
    Region:"/region",
    District:"/district",
    Nationality:"/nationality",
    Profile:"/profile",
    Position:"/position",
    Organizations:"/organizations",
    Worker:"/worker",
    Contact:"/contact",
    ChatWindow:"/chat-window",
    DocumentHistory:"/document-history",
    Exam:"/exam",
    Result: '/result',
    Department:"/department",
    TimeSheet: "/timesheet",
    TimesheetDepartment: "/timesheet-department",
    DepartmentPosition:"/department-position",
    Create:"/create",
    Edit: "/edit",
    Document:"/document",
    ActionLog:"/action-logs",
    Confirmation:"/confirmation",
    DocumentSetting:"/document-setting",
    AdminOther:"/admin-others",
    Schedule:"/schedule",
    Workday:"/workday",
    WorkerProfile:"/worker-profile",
    ConfContract:"/conf-contract",
    ConfCommand:"/conf-command",
    ConfApplication:"/conf-application",
    ConfAdContract:"/conf-ad-contract",
    Topic:"/topic",
    DrawingSignature:"/drawing-signature",
    DocViewer:"/doc-viewer",
    DocumentViewer:"/document-viewer",
    Holiday:"/holiday",
    Questions:"/questions",
    Command:"/command",
    AdContract:"/ad-contract",
    Contract:"/contract",
    Vacation:"/vacation",
    Application:"/application",
    DashboardV2:"/dashboard-v2",
    DashboardV3:"/dashboard-v3",
    Med:"/med",
    Slice:"/slice",
    Turnstile:"/turnstile",
    Building:"/building",
    Terminal:"/terminal",
    Others: "/others",
    Info: "/info",
    OrganizationLeader: '/organization-leader',
    AIConversation: "/ai-conversation",
    Export: "/export",
    BusinessTrip: "/business-trip",
    DocumentArchive: "/document-archive",
    VacationSchedule: "/vacation-schedule",
    WorkerRole: "/worker-role",
    Telegram: "/telegram",
    LearningCenter: "/learning-center",
    Direction: "/direction",
    Specialization: "/specialization",
    Punishment: "/punishment",
    Incentive: "/incentive",
    Report: "/report",
    WorkDuration: "/work-duration",
    Accountant: "/accountant",
    UploadReport: "/upload-report",
}

export const AppLayouts ={
    empty:"empty",
    main:"main",
}