export const appPermissions = {
  users: 'users',
  admin: 'admin',
  usersWrite: 'users-write',
  usersRead: 'users-read',

  roles: 'roles',
  rolesRead: 'roles-read',
  rolesWrite: 'roles-write',

  permissions: 'permissions',
  permissionsRead: 'permissions-read',
  permissionsWrite: 'permissions-write',

  countries: 'countries',
  countriesRead: 'countries-read',
  countriesWrite: 'countries-write',

  regions: 'regions',
  regionsRead: 'regions-read',
  regionsWrite: 'regions-write',

  cities: 'cities',
  citiesRead: 'cities-read',
  citiesWrite: 'cities-write',

  organizations: 'organizations',
  organizationsRead: 'organizations-read',
  organizationsWrite: 'organizations-write',

  documentExamples: 'document-examples',
  documentExamplesRead: 'document-examples-read',
  documentExamplesWrite: 'document-examples-write',

  organizationServices: 'organization-services',
  organizationServicesRead: 'organization-services-read',
  organizationServicesWrite: 'organization-services-write',

  organizationAdmin: 'organization-admin',
  organizationLeader: 'organization-leader',
  organization: 'organization',
  holidays: 'holidays',
  holidaysWrite: 'holidays-write',
  holidaysRead: 'holidays-read',
  universities: 'universities',
  universitiesWrite: 'universities-write',
  universitiesRead: 'universities-read',
  specialities: 'specialities',
  specialitiesWrite: 'specialities-write',
  specialitiesRead: 'specialities-read',
  languages: 'languages',
  languagesWrite: 'languages-write',
  languagesRead: 'languages-read',
  telegram: 'telegram',
  telegramWrite: 'telegram-write',
  telegramRead: 'telegram-read',
  vacancyApprove: 'vacancy-approve',
  vacancyApproveWrite: 'vacancy-approve-write',
  vacancyApproveRead: 'vacancy-approve-read',
  learningCenters: 'learning-centers',
  learningCentersWrite: 'learning-centers-write',
  learningCentersRead: 'learning-centers-read',

  nationalities: 'nationalities',
  nationalitiesWrite: 'nationalities-write',
  nationalitiesRead: 'nationalities-read',
  positions: 'positions',
  positionsWrite: 'positions-write',
  positionsRead: 'positions-read',
  schedules: 'schedules',
  schedulesWrite: 'schedules-write',
  schedulesRead: 'schedules-read',
  workDay: 'work-day',
  workDayWrite: 'work-day-write',
  workDayRead: 'work-day-read',
  activityLogs: 'activity-logs',
  activityLogsWrite: 'activity-logs-write',
  activityLogsRead: 'activity-logs-read',
  instructions: 'instructions',
  instructionsWrite: 'instructions-write',
  instructionsRead: 'instructions-read',

  hr: 'hr',
  hrDashboard: 'hr-dashboard',
  hrDashboardRead: 'hr-dashboard-read',

  hrWorkers: 'hr-workers',
  hrWorkersWrite: 'hr-workers-write',
  hrWorkersRead: 'hr-workers-read',

  hrDepartments: 'hr-departments',
  hrDepartmentsWrite: 'hr-departments-write',
  hrDepartmentsRead: 'hr-departments-read',

  hrPositions: 'hr-positions',
  hrPositionsWrite: 'hr-positions-write',
  hrPositionsRead: 'hr-positions-read',

  hrContracts: 'hr-contracts',
  hrContractsWrite: 'hr-contracts-write',
  hrContractsRead: 'hr-contracts-read',

  hrCommands: 'hr-commands',
  hrCommandsWrite: 'hr-commands-write',
  hrCommandsRead: 'hr-commands-read',
  hrCommandsBlank: 'hr-commands-blank',

  hrContractAdditional: 'hr-contract-additional',
  hrContractAdditionalWrite: 'hr-contract-additional-write',
  hrContractAdditionalRead: 'hr-contract-additional-read',

  hrWorkerApplications: 'hr-worker-applications',
  hrWorkerApplicationsWrite: 'hr-worker-applications-write',
  hrWorkerApplicationsRead: 'hr-worker-applications-read',

  hrConfirmations: 'hr-confirmations',
  hrConfirmationsWrite: 'hr-confirmations-write',
  hrConfirmationsRead: 'hr-confirmations-read',

  hrVacations: 'hr-vacations',
  hrVacationsWrite: 'hr-vacations-write',
  hrVacationsRead: 'hr-vacations-read',

  hrTableWorkers: 'hr-table-workers',
  hrTableWorkersWrite: 'hr-table-workers-write',
  hrTableWorkersRead: 'hr-table-workers-read',

  hrTable: 'hr-table',
  hrTableWrite: 'hr-table-write',
  hrTableRead: 'hr-table-read',

  hrMed: 'hr-med',
  hrMedWrite: 'hr-med-write',
  hrMedRead: 'hr-med-read',

  hrLeaders: 'hr-leaders',
  hrLeadersWrite: 'hr-leaders-write',
  hrLeadersRead: 'hr-leaders-read',

  hrExport: 'hr-export',

  hrBusinessTrip: 'hr-business-trip',
  hrBusinessTripWrite: 'hr-business-trip-write',
  hrBusinessTripRead: 'hr-business-trip-read',

  hrDocuments: 'hr-documents',
  hrDocumentsWrite: 'hr-documents-write',
  hrDocumentsRead: 'hr-documents-read',

  hrVacationSchedule: 'hr-vacation-schedule',
  hrVacationScheduleWrite: 'hr-vacation-schedule-write',
  hrVacationScheduleRead: 'hr-vacation-schedule-read',

  hrUsers: 'hr-users',
  hrUsersWrite: 'hr-users-write',
  hrUsersRead: 'hr-users-read',

  hrPublicVacancy: 'hr-public-vacancy',
  hrPublicVacancyWrite: 'hr-public-vacancy-write',
  hrPublicVacancyRead: 'hr-public-vacancy-read',

  hrReport: 'hr-report',
  hrReportWrite: 'hr-report-write',
  hrReportRead: 'hr-report-read',

  hrReportExport: 'hr-report-export',
  hrReportExportWrite: 'hr-report-export-write',
  hrReportExportRead: 'hr-report-export-read',

  confirmation: 'confirmation',
  confirmationContracts: 'confirmation-contracts',
  confirmationAddContracts: 'confirmation-contract-additional',
  confirmationCommands: 'confirmation-commands',
  confirmationWorkerApplications: 'confirmation-worker-applications',
  confirmationTable: 'confirmation-table',
  confirmationLmsCertificate: 'confirmation-lms-certificate',
  confirmationLmsCertificateRead: 'confirmation-lms-certificate-read',
  confirmationLmsCertificateWrite: 'confirmation-lms-certificate-write',
  confirmationStaffingApproval: 'confirmation-staffing-approval',

  exam: 'exam',

  examTopics: 'exam-topics',
  examTopicsWrite: 'exam-topics-write',
  examTopicsRead: 'exam-topics-read',

  examCategories: 'exam-categories',
  examCategoriesWrite: 'exam-categories-write',
  examCategoriesRead: 'exam-categories-read',

  examExams: 'exam-exams',
  examExamsWrite: 'exam-exams-write',
  examExamsRead: 'exam-exams-read',

  examResults: 'exam-results',
  examResultsWrite: 'exam-results-write',
  examResultsRead: 'exam-results-read',

  turnstile: 'turnstile',
  turnstileBuilding: 'turnstile-building',
  turnstileBuildingWrite: 'turnstile-building-write',
  turnstileBuildingRead: 'turnstile-building-read',
  turnstileTerminal: 'turnstile-terminal',
  turnstileTerminalRead: 'turnstile-terminal-read',
  turnstileTerminalWrite: 'turnstile-terminal-write',
  turnstileOrganization: 'turnstile-organization',
  turnstileOrganizationWrite: 'turnstile-organization-write',
  turnstileOrganizationRead: 'turnstile-organization-read',
  turnstileWorkers: 'turnstile-workers',
  turnstileWorkersWrite: 'turnstile-workers-write',
  turnstileWorkersRead: 'turnstile-workers-read',
  turnstileWorkDuration: 'turnstile-work-duration',
  turnstileWorkDurationRead: 'turnstile-work-duration-read',
  turnstileWorkDurationWrite: 'turnstile-work-duration-write',
  turnstileWorkDurationShow: 'turnstile-work-duration-show',
  turnstileWorkDurationLogs: 'turnstile-work-duration-logs',
  hrJobs: 'hr-jobs',
  hrJobsWrite: 'hr-jobs-write',
  hrJobsRead: 'hr-jobs-read',
  hrMonthlyReport: 'hr-monthly-report',
  exportWorkersZip: 'export-workers-zip',

  turnstileAccessLevels: 'turnstile-access-levels',
  turnstileAccessLevelsRead: 'turnstile-access-levels-read',
  turnstileAccessLevelsWrite: 'turnstile-access-levels-write',
  turnstileOrganizationAccessLevels: 'turnstile-organization-access-levels',
  turnstileOrganizationAccessLevelsRead: 'turnstile-organization-access-levels-read',
  turnstileOrganizationAccessLevelsWrite: 'turnstile-organization-access-levels-write',
  turnstileHikCentralWorkers: 'turnstile-hik-central-workers',
  turnstileHikCentralWorkersRead: 'turnstile-hik-central-workers-read',
  turnstileHikCentralWorkersWrite: 'turnstile-hik-central-workers-write',
  turnstileHikCentralJob: 'turnstile-hik-central-job',
  turnstileHikCentralJobWrite: 'turnstile-hik-central-job-write',
  turnstileHikCentralJobRead: 'turnstile-hik-central-job-read',
  turnstileHikCentralEvents: 'turnstile-hik-central-events',
  turnstileHikCentralEventsRead: 'turnstile-hik-central-events-read',
  turnstileHikCentralEventsWrite: 'turnstile-hik-central-events-write',
  turnstileHikCentralTgUser: 'turnstile-hik-central-tg-user',
  turnstileHikCentralTgUserRead: 'turnstile-hik-central-tg-user-read',
  turnstileHikCentralTgUserWrite: 'turnstile-hik-central-tg-user-write',
  turnstileWorkerImage: 'turnstile-worker-image',
  turnstileWorkerImageRead: 'turnstile-worker-image-read',
  turnstileWorkerImageWrite: 'turnstile-worker-image-write',
  turnstileHikCentralSync: 'turnstile-hik-central-sync',
  turnstileHikCentralSyncWrite: 'turnstile-hik-central-sync-write',
  turnstileHikCentralSyncRead: 'turnstile-hik-central-sync-read',
  turnstileHikCentralUserImageLogs: 'turnstile-hc-user-image-logs',
  turnstileHikCentralInvalidUser: 'turnstile-hc-invalid-user',
  turnstileDevices: 'turnstile-devices',
  turnstileDevicesRead: 'turnstile-devices-read',
  turnstileDevicesWrite: 'turnstile-devices-write',
  turnstileOthers: 'turnstile-others',
  turnstileApprove: 'turnstile-approve',
  turnstileApproveRead: 'turnstile-approve-read',
  turnstileApproveWrite: 'turnstile-approve-write',

  hrIncentives: 'hr-incentives',
  hrIncentivesWrite: 'hr-incentives-write',
  hrIncentivesRead: 'hr-incentives-read',

  hrPunishment: 'hr-discips',
  hrPunishmentWrite: 'hr-discips-write',
  hrPunishmentRead: 'hr-discips-read',
  turnstileDashboard: 'turnstile-dashboard',
  turnstileDashboardRead: 'turnstile-dashboard-read',
  turnstileDashboardWrite: 'turnstile-dashboard-write',

  turnstileHcpDuration: 'turnstile-hcp-duration',
  turnstileHcpDurationShow: 'turnstile-hcp-duration-show',
  turnstileHcpDurationWrite: 'turnstile-hcp-duration-write',
  turnstileHcpDurationRead: 'turnstile-hcp-duration-read',

  turnstileSheetsGroupsWrite: 'turnstile-sheets-groups-write',
  turnstileSheetsGroupsRead: 'turnstile-sheets-groups-read',
  turnstileSheetsGroups: 'turnstile-sheets-groups',
  turnstileSheetsWrite: 'turnstile-sheets-write',
  turnstileSheetsRead: 'turnstile-sheets-read',
  turnstileSheets: 'turnstile-sheets',
  turnstileSheetsWorkersWrite: 'turnstile-sheets-workers-write',
  turnstileSheetsWorkersRead: 'turnstile-sheets-workers-read',
  turnstileSheetsWorkers: 'turnstile-sheets-workers',

  hospital: 'hospital',
  hospitalExpired: 'hospital-expired',
  hospitalExpiredWrite: 'hospital-expired-write',
  hospitalExpiredRead: 'hospital-expired-read',
  hospitalTicket: 'hospital-ticket',
  hospitalTicketWrite: 'hospital-ticket-write',
  hospitalTicketRead: 'hospital-ticket-read',
  hospitalPensioner: 'hospital-pensioner',
  hospitalPensionerRead: 'hospital-pensioner-read',
  hospitalPensionerWrite: 'hospital-pensioner-write',

  useful: 'useful',
  ai: 'ai',
  economist: 'economist',
  economistDashboard: 'economist-dashboard',
  economistWorkerCategories: 'economist-worker-categories',
  economistWorkerCategoriesRead: 'economist-worker-categories-read',
  economistWorkerCategoriesWrite: 'economist-worker-categories-write',
  economistStatements: 'economist-statements',
  economistStatementsWrite: 'economist-statements-write',
  economistStatementsRead: 'economist-statements-read',
  economistStatementsCode: 'economist-statements-code',
  economistTaxFour: 'economist-tax-four',
  economistTaxFourWrite: 'economist-tax-four-write',
  economistTaxFourRead: 'economist-tax-four-read',
  economistTaxFive: 'economist-tax-five',
  economistTaxFiveWrite: 'economist-tax-five-write',
  economistTaxFiveRead: 'economist-tax-five-read',
  economistPensionPayments: 'economist-pension-payments',
  economistPensionPaymentsWrite: 'economist-pension-payments-write',
  economistPensionPaymentsRead: 'economist-pension-payments-read',
  economistUploads: 'economist-uploads',
  economistUploadsWrite: 'economist-uploads-write',
  economistUploadsRead: 'economist-uploads-read',
  economistUploadsConfirm: 'economist-uploads-confirm',
  economistUploadsStatus: 'economist-uploads-status',
  economistStaffingApprove: 'economist-staffing-approve',
  economistStaffingApproveRead: 'economist-staffing-approve-read',
  economistStaffingApproveWrite: 'economist-staffing-approve-write',

  lms: 'lms',
  lmsDirection: 'lms-direction',
  lmsDirectionRead: 'lms-direction-read',
  lmsDirectionWrite: 'lms-direction-write',
  lmsSpecialization: 'lms-specialization',
  lmsSpecializationRead: 'lms-specialization-read',
  lmsSpecializationWrite: 'lms-specialization-write',
  lmsSubjects: 'lms-subjects',
  lmsSubjectsRead: 'lms-subjects-read',
  lmsSubjectsWrite: 'lms-subjects-write',
  lmsEduPlan: 'lms-edu-plan',
  lmsEduPlanRead: 'lms-edu-plan-read',
  lmsEduPlanWrite: 'lms-edu-plan-write',
  lmsTeachers: 'lms-teachers',
  lmsTeachersRead: 'lms-teachers-read',
  lmsTeachersWrite: 'lms-teachers-write',
  lmsGroups: 'lms-groups',
  lmsGroupsRead: 'lms-groups-read',
  lmsGroupsWrite: 'lms-groups-write',
  lmsLessons: 'lms-lessons',
  lmsLessonsRead: 'lms-lessons-read',
  lmsLessonsWrite: 'lms-lessons-write',
  lmsWorker: 'lms-worker',
  lmsWorkerRead: 'lms-worker-read',
  lmsWorkerWrite: 'lms-worker-write',
  lmsCertificate: 'lms-certificate',
  lmsCertificateRead: 'lms-certificate-read',
  lmsCertificateWrite: 'lms-certificate-write',

  chat:'chat',
  chatTelegramMessages:'chat-telegram-messages',
  chatNotification:'chat-notification',

  extra:'extra',
  extraWorkerUser:'extra-worker-user',
  educationsStructureMenu: 'educations-structure-menu',

  departmentLocation: 'department-location',
  departmentLocationRead: 'department-location-read',
  departmentLocationWrite: 'department-location-write',
}
