// AVTO-GENERATSIYA (navigations.js + AppPermissions.js dan). Rol formasi guruhlash.
// Modul (tab) -> sub-menyu (card) -> prefiks. label = menyu i18n kaliti ($t bilan).
// Har guruh <prefix>-read/-write/-delete avtomatik; bo'lmasa bazaviy "Ruxsat" switch.

export const ACTION_LABELS = { read: "Ko'rish", write: 'Yaratish / Tahrirlash', delete: "O'chirish" }
export const ACTION_ORDER = ['read', 'write', 'delete']

export const PERMISSION_GROUPS = [
  {
    module: 'hr',
    label: 'navigation.hrm',
    groups: [
      { prefix: 'hr-dashboard', label: 'dashboardPage.name' },
      { prefix: 'hr-workers', label: 'workerPage.name' },
      { prefix: 'hr-departments', label: 'departmentPage.name' },
      { prefix: 'hr-positions', label: 'departmentPositionPage.name' },
      { prefix: 'hr-contracts', label: 'confirmation.name' },
      { prefix: 'hr-commands', label: 'documentPage.tabs.command' },
      { prefix: 'hr-contract-additional', label: 'documentPage.tabs.adContract' },
      { prefix: 'hr-worker-applications', label: 'applicationPage.name' },
      { prefix: 'hr-confirmations', label: 'confirmationPage.name' },
      { prefix: 'hr-vacations', label: 'vacationPage.name' },
      { prefix: 'hr-table-workers', label: 'timesheetWorkerPage.name' },
      { prefix: 'hr-table', label: 'timesheetPage.name' },
      { prefix: 'hr-med', label: 'medPage.name' },
      { prefix: 'hr-leaders', label: 'organizationLeaderPage.name' },
      { prefix: 'hr-business-trip', label: 'businessTrip.name' },
      { prefix: 'hr-documents', label: 'documentArchive.name' },
      { prefix: 'admin', label: 'vacationSchedule.name' },
      { prefix: 'hr-public-vacancy', label: 'vacancy.name' },
      { prefix: 'hr-discips', label: 'punishment.name' },
      { prefix: 'hr-incentives', label: 'incentive.name' },
      { prefix: 'hr-report', label: 'report.name' },
      { prefix: 'lms-worker', label: 'lmsWorkerPage.name' },
      { prefix: 'hr-report-export', label: 'specialReport.name' },
      { prefix: 'hr-monthly-report', label: 'structureReport.name' },
    ],
  },
  {
    module: 'confirmation',
    label: 'navigation.docFlow',
    groups: [
      { prefix: 'confirmation-contracts', label: 'confirmation.name' },
      { prefix: 'confirmation-commands', label: 'documentPage.tabs.command' },
      { prefix: 'confirmation-contract-additional', label: 'documentPage.tabs.adContract' },
      { prefix: 'confirmation-worker-applications', label: 'applicationPage.name' },
      { prefix: 'confirmation-table', label: 'timesheetPage.name' },
      { prefix: 'admin', label: 'vacationSchedule.name' },
      { prefix: 'confirmation-lms-certificate', label: 'lmsCertificate.name' },
      { prefix: 'confirmation-staffing-approval', label: 'staffingApproval.name' },
      { prefix: 'confirmation', label: 'confirmationReport.name' },
    ],
  },
  {
    module: 'exam',
    label: 'navigation.attestation',
    groups: [
      { prefix: 'exam-topics', label: 'topicPage.name' },
      { prefix: 'exam-categories', label: 'categoryPage.name' },
      { prefix: 'exam-exams', label: 'examPage.name' },
      { prefix: 'exam-results', label: 'examPage.result' },
    ],
  },
  {
    module: 'turnstile',
    label: 'navigation.turnstile',
    groups: [
      { prefix: 'turnstile-dashboard', label: 'turnStileDashboard.name' },
      { prefix: 'turnstile-access-levels', label: 'turnstile.accessLevelPage.name' },
      { prefix: 'turnstile-organization-access-levels', label: 'turnstile.orgAccessLevelsPage.name' },
      { prefix: 'turnstile-hik-central-workers', label: 'turnstile.hcWorkersPage.name' },
      { prefix: 'turnstile-hik-central-events', label: 'hcEvent.name' },
      { prefix: 'turnstile-worker-image', label: 'workerImage.name' },
      { prefix: 'turnstile-devices', label: 'devices.name' },
      { prefix: 'turnstile-others', label: 'additionalPage.name' },
      { prefix: 'turnstile-sheets', label: 'schedule.name' },
      { prefix: 'turnstile-sheets-workers', label: 'shiftType.name' },
      { prefix: 'turnstile-sheets-groups', label: 'shiftType.groupName' },
      { prefix: 'admin', label: 'turnstileSchedule.name' },
      { prefix: 'turnstile-approve', label: 'approve.name' },
    ],
  },
  {
    module: 'lms',
    label: 'navigation.lms',
    groups: [
      { prefix: 'lms-direction', label: 'directionPage.name' },
      { prefix: 'lms-specialization', label: 'specializationPage.name' },
      { prefix: 'lms-subjects', label: 'subjectPage.name' },
      { prefix: 'lms-edu-plan', label: 'eduPlanPage.name' },
      { prefix: 'lms-teachers', label: 'teacherPage.name' },
      { prefix: 'lms-lessons', label: 'lessonPage.name' },
      { prefix: 'admin', label: 'teacherLesson.name' },
      { prefix: 'lms-certificate', label: 'lmsCertificate.name' },
    ],
  },
  {
    module: 'economist',
    label: 'navigation.economist',
    groups: [
      { prefix: 'economist-dashboard', label: 'accDashboard.name' },
      { prefix: 'economist-worker-categories', label: 'salaryCategory.name' },
      { prefix: 'economist-uploads', label: 'uploadReport.name' },
      { prefix: 'economist-statements', label: 'monthReport.name' },
      { prefix: 'economist-statements-code', label: 'salaryReport.name' },
      { prefix: 'economist-tax-four', label: 'taxFour.name' },
      { prefix: 'economist-tax-five', label: 'taxFive.name' },
      { prefix: 'economist-pension-payments', label: 'pensionPayment.name' },
      { prefix: 'hr-report', label: 'report.name' },
      { prefix: 'economist-staffing-approve', label: 'staffingApproval.name' },
    ],
  },
  {
    module: 'hospital',
    label: 'navigation.hospital',
    groups: [
      { prefix: 'hospital-expired', label: 'expiredHealth.name' },
      { prefix: 'hospital-ticket', label: 'ticket.name' },
      { prefix: 'hospital-pensioner', label: 'pensioner.name' },
    ],
  },
  {
    module: 'admin',
    label: 'navigation.chat',
    groups: [
      { prefix: 'instructions', label: 'notificationPage.name' },
      { prefix: 'admin', label: 'newsPage.name' },
      { prefix: 'chat-telegram-messages', label: 'congratulation.name' },
    ],
  },
  {
    module: 'extra',
    label: 'navigation.extra',
    groups: [
      { prefix: 'extra-worker-user', label: 'workerRole.name' },
      { prefix: 'educations-structure-menu', label: 'educationDirectory.name' },
      { prefix: 'department-location', label: 'departmentLocationPage.name' },
    ],
  },
  {
    module: 'admin',
    label: 'navigation.admin',
    groups: [
      { prefix: 'users', label: 'userPage.name' },
      { prefix: 'roles', label: 'userRole.name' },
      { prefix: 'permissions', label: 'userPermission.name' },
      { prefix: 'countries', label: 'countryPage.name' },
      { prefix: 'regions', label: 'regionPage.name' },
      { prefix: 'cities', label: 'districtPage.name' },
      { prefix: 'nationalities', label: 'nationalityPage.name' },
      { prefix: 'positions', label: 'positionPage.name' },
      { prefix: 'schedules', label: 'schedulePage.name' },
      { prefix: 'work-day', label: 'workdayPage.name' },
      { prefix: 'organizations', label: 'organizationPage.name' },
      { prefix: 'activity-logs', label: 'actionLog.name' },
      { prefix: 'document-examples', label: 'documentSetting.name' },
      { prefix: 'holidays', label: 'holidayPage.name' },
      { prefix: 'universities', label: 'othersPage.name' },
      { prefix: 'telegram', label: 'telegramPage.name' },
      { prefix: 'learning-centers', label: 'learningCenterPage.name' },
      { prefix: 'instructions', label: 'instructionPage.name' },
      { prefix: 'admin', label: 'mobileUserPage.name' },
    ],
  },
]
