// AVTO-GENERATSIYA (navigations.js + AppPermissions.js dan). Rol formasi guruhlash.
// Modul (tab) -> sub-menyu (card) -> prefiks. label = menyu i18n kaliti ($t bilan).
// Har guruh <prefix>-read/-write/-delete avtomatik; bo'lmasa bazaviy "Ruxsat" switch.

export const ACTION_LABELS = { read: "Ko'rish", write: 'Yaratish / Tahrirlash', delete: "O'chirish" }
export const ACTION_ORDER = ['read', 'write', 'delete']

// AVTO-GENERATSIYA: backend @Permission (enforce qilinadigan) + frontend AppPermissions
// (haqiqatan ishlatilgan) sluglar birlashmasi. Forma faqat SHU sluglarga switch
// ko'rsatadi — DB'da bor-u hech qayerda ishlatilmaydigan (spurious) sluglar yashiriladi.
export const MEANINGFUL = new Set([
  'activity-logs', 'activity-logs-read', 'admin', 'ai', 'authentication-logs-read', 'chat-news-delete',
  'chat-notification', 'chat-telegram-messages', 'cities', 'cities-delete', 'cities-read', 'cities-write',
  'confirmation', 'confirmation-commands', 'confirmation-contract-additional', 'confirmation-contracts', 'confirmation-documents-delete', 'confirmation-lms-certificate',
  'confirmation-lms-certificate-read', 'confirmation-staffing-approval', 'confirmation-table', 'confirmation-worker-applications', 'confirmation-worker-applications-delete', 'countries',
  'countries-delete', 'countries-read', 'countries-write', 'department-location', 'deploy-read', 'deploy-write',
  'document-examples', 'document-examples-read', 'document-examples-write', 'document-view-exam-results', 'economist', 'economist-dashboard',
  'economist-dashboard-read', 'economist-pension-payments', 'economist-pension-payments-delete', 'economist-pension-payments-read', 'economist-pension-payments-write', 'economist-staffing-approve',
  'economist-staffing-approve-read', 'economist-staffing-approve-write', 'economist-staffing-delete', 'economist-staffing-read', 'economist-staffing-write', 'economist-statements',
  'economist-statements-code', 'economist-statements-delete', 'economist-statements-read', 'economist-statements-write', 'economist-tax-five', 'economist-tax-five-delete',
  'economist-tax-five-read', 'economist-tax-five-write', 'economist-tax-four', 'economist-tax-four-delete', 'economist-tax-four-read', 'economist-tax-four-write',
  'economist-uploads', 'economist-uploads-confirm', 'economist-uploads-read', 'economist-uploads-status', 'economist-uploads-write', 'economist-worker-categories',
  'economist-worker-categories-delete', 'economist-worker-categories-read', 'economist-worker-categories-write', 'educations-structure-menu', 'exam', 'exam-categories',
  'exam-categories-delete', 'exam-categories-read', 'exam-categories-write', 'exam-exams', 'exam-exams-delete', 'exam-exams-read',
  'exam-exams-write', 'exam-results', 'exam-results-read', 'exam-topics', 'exam-topics-delete', 'exam-topics-read',
  'exam-topics-write', 'export-workers-zip', 'extra', 'extra-worker-user', 'filter-search-workers', 'holiday-greetings-delete',
  'holiday-greetings-read', 'holiday-greetings-write', 'holidays', 'holidays-delete', 'holidays-read', 'holidays-write',
  'hospital', 'hospital-expired', 'hospital-pensioner', 'hospital-pensioner-read', 'hospital-pensioner-write', 'hospital-ticket',
  'hr', 'hr-business-trip', 'hr-business-trip-read', 'hr-business-trip-write', 'hr-check-worker', 'hr-commands',
  'hr-commands-blank', 'hr-commands-delete', 'hr-commands-read', 'hr-commands-write', 'hr-confirmations', 'hr-confirmations-delete',
  'hr-confirmations-read', 'hr-confirmations-write', 'hr-contract-additional', 'hr-contract-additional-delete', 'hr-contract-additional-read', 'hr-contract-additional-write',
  'hr-contracts', 'hr-contracts-delete', 'hr-contracts-read', 'hr-contracts-write', 'hr-dashboard', 'hr-dashboard-read',
  'hr-department-locations-delete', 'hr-department-locations-read', 'hr-department-locations-write', 'hr-departments', 'hr-departments-delete', 'hr-departments-read',
  'hr-departments-write', 'hr-discips', 'hr-discips-read', 'hr-documents', 'hr-documents-delete', 'hr-documents-read',
  'hr-documents-write', 'hr-edu-plans-read', 'hr-edu-plans-write', 'hr-export', 'hr-incentives', 'hr-incentives-read',
  'hr-incentives-write', 'hr-jobs', 'hr-jobs-read', 'hr-language-certificates-delete', 'hr-language-certificates-read', 'hr-language-certificates-write',
  'hr-leaders', 'hr-leaders-delete', 'hr-leaders-read', 'hr-leaders-write', 'hr-med', 'hr-med-delete',
  'hr-med-read', 'hr-med-write', 'hr-monthly-report', 'hr-monthly-report-delete', 'hr-nationalities-delete', 'hr-nationalities-write',
  'hr-organization-phones-delete', 'hr-organization-phones-read', 'hr-organization-phones-write', 'hr-pensioners-delete', 'hr-pensioners-read', 'hr-pensioners-write',
  'hr-polyclinics-delete', 'hr-polyclinics-read', 'hr-polyclinics-write', 'hr-positions', 'hr-positions-delete', 'hr-positions-read',
  'hr-positions-write', 'hr-public-vacancy', 'hr-public-vacancy-delete', 'hr-public-vacancy-read', 'hr-public-vacancy-write', 'hr-report',
  'hr-report-delete', 'hr-report-export', 'hr-report-export-delete', 'hr-report-management-write', 'hr-report-read', 'hr-report-write',
  'hr-table', 'hr-table-delete', 'hr-table-read', 'hr-table-workers', 'hr-table-workers-read', 'hr-table-workers-write',
  'hr-table-write', 'hr-users-read', 'hr-users-write', 'hr-vacation-schedule-delete', 'hr-vacation-schedule-read', 'hr-vacation-schedule-write',
  'hr-vacations', 'hr-vacations-read', 'hr-vacations-write', 'hr-worker-applications', 'hr-worker-applications-read', 'hr-worker-applications-write',
  'hr-workers', 'hr-workers-delete', 'hr-workers-read', 'hr-workers-write', 'hr-zoom-write', 'instructions',
  'instructions-delete', 'instructions-read', 'instructions-write', 'integration', 'integration-clients-delete', 'integration-clients-read',
  'integration-clients-write', 'languages-delete', 'languages-read', 'languages-write', 'learning-centers', 'learning-centers-delete',
  'learning-centers-read', 'learning-centers-write', 'lms', 'lms-certificate', 'lms-certificate-delete', 'lms-certificate-read',
  'lms-certificate-write', 'lms-direction', 'lms-direction-delete', 'lms-direction-read', 'lms-direction-write', 'lms-edu-plan',
  'lms-edu-plan-delete', 'lms-edu-plan-read', 'lms-edu-plan-write', 'lms-groups-read', 'lms-groups-write', 'lms-lessons',
  'lms-lessons-delete', 'lms-lessons-read', 'lms-lessons-write', 'lms-specialization', 'lms-specialization-delete', 'lms-specialization-read',
  'lms-specialization-write', 'lms-subjects', 'lms-subjects-delete', 'lms-subjects-read', 'lms-subjects-write', 'lms-teachers',
  'lms-teachers-delete', 'lms-teachers-read', 'lms-teachers-write', 'lms-worker', 'lms-worker-read', 'lms-worker-write',
  'log-viewer-read', 'mobile-stories-delete', 'mobile-users-read', 'nationalities', 'nationalities-read', 'nationalities-write',
  'organization-services-write', 'organizations', 'organizations-delete', 'organizations-read', 'organizations-write', 'permissions',
  'permissions-delete', 'permissions-read', 'permissions-write', 'positions', 'positions-delete', 'positions-read',
  'positions-write', 'quotes-delete', 'quotes-write', 'regions', 'regions-delete', 'regions-read',
  'regions-write', 'roles', 'roles-delete', 'roles-read', 'roles-write', 'schedules',
  'schedules-delete', 'schedules-read', 'schedules-write', 'specialities-delete', 'specialities-read', 'specialities-write',
  'telegram', 'telegram-read', 'telegram-write', 'turnstile', 'turnstile-absent-workers-export', 'turnstile-access-levels',
  'turnstile-access-levels-read', 'turnstile-access-levels-write', 'turnstile-approve', 'turnstile-approve-delete', 'turnstile-approve-read', 'turnstile-approve-write',
  'turnstile-building', 'turnstile-building-delete', 'turnstile-building-read', 'turnstile-building-write', 'turnstile-dashboard', 'turnstile-dashboard-read',
  'turnstile-devices', 'turnstile-devices-delete', 'turnstile-devices-read', 'turnstile-devices-write', 'turnstile-hc-invalid-user', 'turnstile-hc-user-image-logs',
  'turnstile-hcp-duration', 'turnstile-hcp-duration-read', 'turnstile-hik-central-events', 'turnstile-hik-central-events-read', 'turnstile-hik-central-job', 'turnstile-hik-central-job-read',
  'turnstile-hik-central-job-write', 'turnstile-hik-central-sync', 'turnstile-hik-central-sync-read', 'turnstile-hik-central-sync-write', 'turnstile-hik-central-tg-user', 'turnstile-hik-central-tg-user-delete',
  'turnstile-hik-central-tg-user-read', 'turnstile-hik-central-tg-user-write', 'turnstile-hik-central-workers', 'turnstile-hik-central-workers-delete', 'turnstile-hik-central-workers-read', 'turnstile-hik-central-workers-write',
  'turnstile-organization', 'turnstile-organization-access-levels', 'turnstile-organization-access-levels-read', 'turnstile-organization-access-levels-write', 'turnstile-organization-read', 'turnstile-organization-write',
  'turnstile-others', 'turnstile-sheets', 'turnstile-sheets-delete', 'turnstile-sheets-groups', 'turnstile-sheets-groups-delete', 'turnstile-sheets-groups-read',
  'turnstile-sheets-groups-write', 'turnstile-sheets-read', 'turnstile-sheets-workers', 'turnstile-sheets-workers-delete', 'turnstile-sheets-workers-read', 'turnstile-sheets-workers-write',
  'turnstile-sheets-write', 'turnstile-terminal', 'turnstile-terminal-delete', 'turnstile-terminal-read', 'turnstile-terminal-write', 'turnstile-work-duration',
  'turnstile-work-duration-read', 'turnstile-worker-image', 'turnstile-workers', 'turnstile-workers-read', 'turnstile-workers-write', 'universities',
  'universities-delete', 'universities-read', 'universities-write', 'useful', 'users', 'users-delete',
  'users-read', 'users-write', 'vacancy-approve-delete', 'work-day', 'work-day-delete', 'work-day-read',
  'work-day-write',
])

export const PERMISSION_GROUPS = [
  {
    module: 'hr',
    label: 'navigation.hrm',
    groups: [
      { prefix: 'hr-dashboard', label: 'dashboardPage.name' },
      { prefix: 'hr-workers', label: 'workerPage.name' },
      { prefix: 'hr-departments', label: 'departmentPage.name' },
      { prefix: 'hr-positions', label: 'departmentPositionPage.name' },
      { prefix: 'hr-contracts', label: 'confirmation.name' },
      { prefix: 'hr-commands', label: 'documentPage.tabs.command' },
      { prefix: 'hr-contract-additional', label: 'documentPage.tabs.adContract' },
      { prefix: 'hr-worker-applications', label: 'applicationPage.name' },
      { prefix: 'hr-confirmations', label: 'confirmationPage.name' },
      { prefix: 'hr-vacations', label: 'vacationPage.name' },
      { prefix: 'hr-table-workers', label: 'timesheetWorkerPage.name' },
      { prefix: 'hr-table', label: 'timesheetPage.name' },
      { prefix: 'hr-med', label: 'medPage.name' },
      { prefix: 'hr-leaders', label: 'organizationLeaderPage.name' },
      { prefix: 'hr-business-trip', label: 'businessTrip.name' },
      { prefix: 'hr-documents', label: 'documentArchive.name' },
      { prefix: 'admin', label: 'vacationSchedule.name' },
      { prefix: 'hr-public-vacancy', label: 'vacancy.name' },
      { prefix: 'hr-discips', label: 'punishment.name' },
      { prefix: 'hr-incentives', label: 'incentive.name' },
      { prefix: 'hr-report', label: 'report.name' },
      { prefix: 'lms-worker', label: 'lmsWorkerPage.name' },
      { prefix: 'hr-report-export', label: 'specialReport.name' },
      { prefix: 'hr-monthly-report', label: 'structureReport.name' },
    ],
  },
  {
    module: 'confirmation',
    label: 'navigation.docFlow',
    groups: [
      { prefix: 'confirmation-contracts', label: 'confirmation.name' },
      { prefix: 'confirmation-commands', label: 'documentPage.tabs.command' },
      { prefix: 'confirmation-contract-additional', label: 'documentPage.tabs.adContract' },
      { prefix: 'confirmation-worker-applications', label: 'applicationPage.name' },
      { prefix: 'confirmation-table', label: 'timesheetPage.name' },
      { prefix: 'admin', label: 'vacationSchedule.name' },
      { prefix: 'confirmation-lms-certificate', label: 'lmsCertificate.name' },
      { prefix: 'confirmation-staffing-approval', label: 'staffingApproval.name' },
      { prefix: 'confirmation', label: 'confirmationReport.name' },
    ],
  },
  {
    module: 'exam',
    label: 'navigation.attestation',
    groups: [
      { prefix: 'exam-topics', label: 'topicPage.name' },
      { prefix: 'exam-categories', label: 'categoryPage.name' },
      { prefix: 'exam-exams', label: 'examPage.name' },
      { prefix: 'exam-results', label: 'examPage.result' },
    ],
  },
  {
    module: 'turnstile',
    label: 'navigation.turnstile',
    groups: [
      { prefix: 'turnstile-dashboard', label: 'turnStileDashboard.name' },
      { prefix: 'turnstile-access-levels', label: 'turnstile.accessLevelPage.name' },
      { prefix: 'turnstile-organization-access-levels', label: 'turnstile.orgAccessLevelsPage.name' },
      { prefix: 'turnstile-hik-central-workers', label: 'turnstile.hcWorkersPage.name' },
      { prefix: 'turnstile-hik-central-events', label: 'hcEvent.name' },
      { prefix: 'turnstile-worker-image', label: 'workerImage.name' },
      { prefix: 'turnstile-devices', label: 'devices.name' },
      { prefix: 'turnstile-others', label: 'additionalPage.name' },
      { prefix: 'turnstile-sheets', label: 'schedule.name' },
      { prefix: 'turnstile-sheets-workers', label: 'shiftType.name' },
      { prefix: 'turnstile-sheets-groups', label: 'shiftType.groupName' },
      { prefix: 'admin', label: 'turnstileSchedule.name' },
      { prefix: 'turnstile-approve', label: 'approve.name' },
    ],
  },
  {
    module: 'lms',
    label: 'navigation.lms',
    groups: [
      { prefix: 'lms-direction', label: 'directionPage.name' },
      { prefix: 'lms-specialization', label: 'specializationPage.name' },
      { prefix: 'lms-subjects', label: 'subjectPage.name' },
      { prefix: 'lms-edu-plan', label: 'eduPlanPage.name' },
      { prefix: 'lms-teachers', label: 'teacherPage.name' },
      { prefix: 'lms-lessons', label: 'lessonPage.name' },
      { prefix: 'admin', label: 'teacherLesson.name' },
      { prefix: 'lms-certificate', label: 'lmsCertificate.name' },
    ],
  },
  {
    module: 'economist',
    label: 'navigation.economist',
    groups: [
      { prefix: 'economist-dashboard', label: 'accDashboard.name' },
      { prefix: 'economist-worker-categories', label: 'salaryCategory.name' },
      { prefix: 'economist-uploads', label: 'uploadReport.name' },
      { prefix: 'economist-statements', label: 'monthReport.name' },
      { prefix: 'economist-statements-code', label: 'salaryReport.name' },
      { prefix: 'economist-tax-four', label: 'taxFour.name' },
      { prefix: 'economist-tax-five', label: 'taxFive.name' },
      { prefix: 'economist-pension-payments', label: 'pensionPayment.name' },
      { prefix: 'hr-report', label: 'report.name' },
      { prefix: 'economist-staffing-approve', label: 'staffingApproval.name' },
    ],
  },
  {
    module: 'hospital',
    label: 'navigation.hospital',
    groups: [
      { prefix: 'hospital-expired', label: 'expiredHealth.name' },
      { prefix: 'hospital-ticket', label: 'ticket.name' },
      { prefix: 'hospital-pensioner', label: 'pensioner.name' },
    ],
  },
  {
    module: 'admin',
    label: 'navigation.chat',
    groups: [
      { prefix: 'instructions', label: 'notificationPage.name' },
      { prefix: 'admin', label: 'newsPage.name' },
      { prefix: 'chat-telegram-messages', label: 'congratulation.name' },
    ],
  },
  {
    module: 'extra',
    label: 'navigation.extra',
    groups: [
      { prefix: 'extra-worker-user', label: 'workerRole.name' },
      { prefix: 'educations-structure-menu', label: 'educationDirectory.name' },
      { prefix: 'department-location', label: 'departmentLocationPage.name' },
    ],
  },
  {
    module: 'admin',
    label: 'navigation.admin',
    groups: [
      { prefix: 'users', label: 'userPage.name' },
      { prefix: 'roles', label: 'userRole.name' },
      { prefix: 'permissions', label: 'userPermission.name' },
      { prefix: 'countries', label: 'countryPage.name' },
      { prefix: 'regions', label: 'regionPage.name' },
      { prefix: 'cities', label: 'districtPage.name' },
      { prefix: 'nationalities', label: 'nationalityPage.name' },
      { prefix: 'positions', label: 'positionPage.name' },
      { prefix: 'schedules', label: 'schedulePage.name' },
      { prefix: 'work-day', label: 'workdayPage.name' },
      { prefix: 'organizations', label: 'organizationPage.name' },
      { prefix: 'activity-logs', label: 'actionLog.name' },
      { prefix: 'document-examples', label: 'documentSetting.name' },
      { prefix: 'holidays', label: 'holidayPage.name' },
      { prefix: 'universities', label: 'othersPage.name' },
      { prefix: 'telegram', label: 'telegramPage.name' },
      { prefix: 'learning-centers', label: 'learningCenterPage.name' },
      { prefix: 'instructions', label: 'instructionPage.name' },
      { prefix: 'admin', label: 'mobileUserPage.name' },
    ],
  },
]
